name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Обновление pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt

      - name: Проверка версии Python
        run: python --version

      - name: Запуск вашего скрипта или тестов
        run: |
          # например, запуск вашего приложения или тестов
          python streamlit_app.py
